from django.conf.urls.defaults import *
import settings

urlpatterns = patterns('',
                       # Info pages
                       (r'^$', 'opinion.opinion_core.views.app'),
                       (r'^(\w+)$', 'opinion.opinion_core.views.app'), 
                       (r'^app/$', 'opinion.opinion_core.views.app'), 

                       (r'^mobile/$', 'opinion.opinion_core.views.mobile'),
                       (r'^mobile/(?P<entry_code>\w+)/$', 'opinion.opinion_core.views.mobile'),
                       (r'^app/(\w+)/$', 'opinion.opinion_core.views.app'),
                       (r'^crcstats/$', 'opinion.opinion_core.views.crcstats'),
                       (r'^crcstats/(?P<entry_code>\w+)/$', 'opinion.opinion_core.views.crcstats'),
                       (r'^getallstats/$', 'opinion.opinion_core.views.getallstats'),
                       #(r'^about/$', 'opinion.opinion_core.views.about'),
                       #(r'^feedback/$', 'opinion.opinion_core.views.feedback'),
                       #(r'^suggestion/$', 'opinion.opinion_core.views.suggestion'),
                       #(r'^sampleiframe/$', 'opinion.opinion_core.views.sample_iframe'),
                       #(r'^home/$', 'opinion.opinion_core.views.app'), # change back to home later
                       #(r'^opinion-space-2.0/$', 'opinion.opinion_core.views.app'),
                       #(r'^newcontent/$', 'opinion.opinion_core.views.newcontent'),
                       (r'^seed/$', 'opinion.opinion_core.views.seed_client'),
                       #(r'^opinion-space-2.1-hidden/$', 'opinion.opinion_core.views.new_content_banner'),
                       #(r'^solid_nofilter/$', 'opinion.opinion_core.views.solid_nofilter'),
                       #(r'^contact/$', 'opinion.opinion_core.views.contact'),
                       
                       # Admin panel methods
                       (r'^adminpanel/overview/$', 'opinion.opinion_core.views.get_overview'),
                       (r'^adminpanel/flaggedcomments/$', 'opinion.opinion_core.views.get_flaggedcomments'),
                       (r'^adminpanel/blacklisteduser/$', 'opinion.opinion_core.views.get_blacklisteduser'),
                       (r'^adminpanel/highvariance/$', 'opinion.opinion_core.views.get_highvariancecomments'),
                       (r'^adminpanel/newadditions/$', 'opinion.opinion_core.views.get_newadditions'),
                       (r'^adminpanel/search/$', 'opinion.opinion_core.views.get_search'),
                       (r'^adminpanel/loginerror/$', 'opinion.opinion_core.views.get_loginerror'),
                       (r'^admincontent/(\d+)/(\d+)/$', 'opinion.opinion_core.views.get_admin_content'),
                       (r'^admincontent/(\d+)/$', 'opinion.opinion_core.views.get_admin_content'),	
                       (r'^approvecomment/(\d+)/$', 'opinion.opinion_core.views.approve_comment'),
                       (r'^blacklist/(\d+)/$', 'opinion.opinion_core.views.blacklist_comment'),
                       (r'^unblacklist/(\d+)/$', 'opinion.opinion_core.views.unblacklist_comment'),
                       (r'^banish/(\d+)/$', 'opinion.opinion_core.views.banish_user'),
                       (r'^search/(\d+)/$', 'opinion.opinion_core.views.search'),
                       (r'^search/(\d+)/(\w*)/$', 'opinion.opinion_core.views.search'),
                       (r'^newusers/(\d+)/(\d+)/$', 'opinion.opinion_core.views.get_new_users'),
                       (r'^adminpanel/blacklistedcomments/$', 'opinion.opinion_core.views.get_blacklistedcomments'),
                       (r'^adminpanel/bannedusers/$', 'opinion.opinion_core.views.get_bannedusers'),
                       (r'^adminpanel/userdetails/$', 'opinion.opinion_core.views.get_userdetails'),
                       (r'^adminpanel/statistics/$', 'opinion.opinion_core.views.get_statistics'),
                       (r'^adminpanel/generateplot/$', 'opinion.opinion_core.views.custom_statistics'),
                       (r'^adminpanel/getdata/(?P<timeperiod>\w{0,50})/$', 'opinion.opinion_core.views.get_adminpanel_stats'),
                       (r'^adminpanel/subgroup/$', 'opinion.opinion_core.views.get_subgroupplot'),
                       (r'^adminpanel/getsubgroup/$', 'opinion.opinion_core.views.get_subgroup_data'),
                       (r'^adminpanel/suggestion/$', 'opinion.opinion_core.views.get_suggestions'),
                       (r'^adminpanel/configure/$', 'opinion.opinion_core.views.configure_client'),
                       (r'^adminpanel/install/$', 'opinion.opinion_core.views.install_client'),
                       (r'^adminpanel/proofread/$', 'opinion.opinion_core.views.proof_read_comments'),
                       (r'^adminpanel/$', 'opinion.opinion_core.views.admin_panel_login'),

                       # JSON pages
                       #(r'^os/list/$', 'opinion.opinion_core.views.os_list'),
                       (r'^os/show/(\d+)/$', 'opinion.opinion_core.views.os_show'),
                       (r'^os/show/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_show'),
                       (r'^os/testAuth/$', 'opinion.opinion_core.views.os_test_auth'),
                       #(r'^os/otherusers/(\d+)/$', 'opinion.opinion_core.views.os_other_users'),
                       #(r'^os/otherusers/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_other_users'),

                       #(r'^os/all/(\d+)/$', 'opinion.opinion_core.views.os_all_current_comments'),
                       #(r'^os/all/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_all_current_comments'),
                       #(r'^os/unrated/(\d+)/$', 'opinion.opinion_core.views.os_unrated_comments'),
                       #(r'^os/unrated/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_unrated_comments'),
                       #(r'^os/leaderboard/(\d+)/$', 'opinion.opinion_core.views.os_leaderboard_comments'),
                       #(r'^os/leaderboard/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_leaderboard_comments'),
                       #(r'^os/rated/(\d+)/$', 'opinion.opinion_core.views.os_rated_comments'),
                       #(r'^os/rated/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_rated_comments'),
                       (r'^os/ratedby/(\d+)/$', 'opinion.opinion_core.views.os_rated_by_comments'),
                       (r'^os/ratedby/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_rated_by_comments'),
                       #(r'^os/userlist/(\d+)/$', 'opinion.opinion_core.views.os_user_list'),
                       #(r'^os/userlist/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_user_list'),
                       #(r'^os/landmarks/(\d+)/$', 'opinion.opinion_core.views.os_landmarks'),
                       #(r'^os/getpreviouscomment/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_get_previous_comment'),
                       #(r'^os/getuserinfo/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_get_user_info'),
                       #(r'^os/getlandmarkratings/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_get_landmark_ratings'),
                       #(r'^os/getcomment/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_get_comment'),
                       #(r'^os/getcomment/(\d+)/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_get_comment'),
                       #(r'^os/getreceivedsuggestions/(\d+)/$', 'opinion.opinion_core.views.os_get_received_suggestions'),
                       #(r'^os/getreceivedsuggestions/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_get_received_suggestions'),
                       #(r'^os/getgivensuggestions/(\d+)/$', 'opinion.opinion_core.views.os_get_given_suggestions'),
                       #(r'^os/getgivensuggestions/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_get_given_suggestions'),
                       #(r'^os/savesuggestionrating/$', 'opinion.opinion_core.views.os_save_suggestion_rating'),
                       (r'^os/flagcomment/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_flag_comment'),
                       (r'^os/saveratings/(\d+)/$', 'opinion.opinion_core.views.os_save_ratings'),
                       (r'^os/saverating/(\d+)/$', 'opinion.opinion_core.views.os_save_rating'),
                       (r'^os/savecomment/(\d+)/$', 'opinion.opinion_core.views.os_save_comment'),
                       (r'^os/savecomment/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_save_comment'),
                       (r'^os/savecommentrating/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_save_comment_rating'),
                       (r'^os/savecommentrating/(\d+)/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_save_comment_rating'),
                       (r'^os/savecommentagreement/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_save_comment_agreement'),
                       (r'^os/savecommentagreement/(\d+)/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_save_comment_agreement'),
                       #(r'^os/savesuggestion/$', 'opinion.opinion_core.views.os_save_comment_suggestion'),
                       #(r'^os/updateusersettings/$', 'opinion.opinion_core.views.os_update_user_settings'),
                       #(r'^os/firsttime/(\d+)/$', 'opinion.opinion_core.views.os_save_first_time_ratings'),
                       (r'^os/stats/(\d+)/$', 'opinion.opinion_core.views.get_stats'),
                       (r'^os/stats/(\d+)/(\d+)/$', 'opinion.opinion_core.views.get_stats'),
                       #(r'^os/notifications/(\d+)/$', 'opinion.opinion_core.views.get_notifications'),
                       #(r'^os/notifications/(\d+)/(\d+)/$', 'opinion.opinion_core.views.get_notifications'),
                       #(r'^os/neverseencomments/(\d+)/$', 'opinion.opinion_core.views.os_never_seen_comments'),
                       #(r'^os/neverseencomments/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_never_seen_comments'),
                       #(r'^os/ratedupdatedcomments/(\d+)/$', 'opinion.opinion_core.views.os_rated_updated_comments'),
                       #(r'^os/ratedupdatedcomments/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_rated_updated_comments'),
                       #(r'^os/updatecomment/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_update_comment'),
                       #(r'^os/updatecomment/(\d+)/(\d+)/(\d+)/$', 'opinion.opinion_core.views.os_update_comment'),
                       
                       #send confirmation email with entry code
                       (r'^confirmationmail/$','opinion.opinion_core.views.confirmation_mail'),
                       #get neighborhood statistic
                       (r'^neighborhoodStat/$','opinion.opinion_core.views.neighbor_stat'),
                       # Admin
                       #(r'^admin/comments/$', 'opinion.opinion_core.admin.comment_admin'),
                       # New Logs
                       (r'^log/httperror/$', 'opinion.opinion_core.views.log_http_error'),
                       (r'^log/userevent/$', 'opinion.opinion_core.views.log_user_event'),
                       (r'^log/commentview/$', 'opinion.opinion_core.views.log_comment_view'),
                       (r'^log/firsttime/$', 'opinion.opinion_core.views.os_first_time_log'),
                       # SMS
                       #(r'^os/receivesms/$', 'opinion.opinion_core.views.os_receive_sms_comment'),
                       
                       #Close
                       #(r'^os/applicationclose/$', 'opinion.opinion_core.views.application_close'),
                       )
