from django.conf.urls.defaults import *
import settings

urlpatterns = patterns('',
    # Info pages
    (r'^$', 'cafe.cafe_core.views.app'),
    (r'^(\w+)$', 'cafe.cafe_core.views.app'), 
    (r'^app/$', 'cafe.cafe_core.views.app'), 

    (r'^mobile/$', 'cafe.cafe_core.views.mobile'), 

    (r'^app/(\w+)/$', 'cafe.cafe_core.views.app'), 
    (r'^about/$', 'cafe.cafe_core.views.about'),
    (r'^feedback/$', 'cafe.cafe_core.views.feedback'),
    (r'^suggestion/$', 'cafe.cafe_core.views.suggestion'),
    (r'^sampleiframe/$', 'cafe.cafe_core.views.sample_iframe'),
    (r'^home/$', 'cafe.cafe_core.views.app'), # change back to home later
    (r'^cafe-space-2.0/$', 'cafe.cafe_core.views.app'),	
    (r'^newcontent/$', 'cafe.cafe_core.views.newcontent'),	
    (r'^seed/$', 'cafe.cafe_core.views.seed_client'),
    (r'^cafe-space-2.1-hidden/$', 'cafe.cafe_core.views.new_content_banner'),
    (r'^solid_nofilter/$', 'cafe.cafe_core.views.solid_nofilter'),
    #(r'^contact/$', 'cafe.cafe_core.views.contact'),
	
	# Admin panel methods
	(r'^adminpanel/overview/$', 'cafe.cafe_core.views.get_overview'),
	(r'^adminpanel/flaggedcomments/$', 'cafe.cafe_core.views.get_flaggedcomments'),
	(r'^adminpanel/blacklisteduser/$', 'cafe.cafe_core.views.get_blacklisteduser'),
	(r'^adminpanel/highvariance/$', 'cafe.cafe_core.views.get_highvariancecomments'),
	(r'^adminpanel/newadditions/$', 'cafe.cafe_core.views.get_newadditions'),
	(r'^adminpanel/search/$', 'cafe.cafe_core.views.get_search'),
	(r'^adminpanel/loginerror/$', 'cafe.cafe_core.views.get_loginerror'),
    (r'^admincontent/(\d+)/(\d+)/$', 'cafe.cafe_core.views.get_admin_content'),
    (r'^admincontent/(\d+)/$', 'cafe.cafe_core.views.get_admin_content'),	
    (r'^approvecomment/(\d+)/$', 'cafe.cafe_core.views.approve_comment'),
    (r'^blacklist/(\d+)/$', 'cafe.cafe_core.views.blacklist_comment'),
    (r'^unblacklist/(\d+)/$', 'cafe.cafe_core.views.unblacklist_comment'),
    (r'^banish/(\d+)/$', 'cafe.cafe_core.views.banish_user'),
    (r'^search/(\d+)/(\w+)/$', 'cafe.cafe_core.views.search'),
    (r'^newusers/(\d+)/(\d+)/$', 'cafe.cafe_core.views.get_new_users'),
	(r'^adminpanel/blacklistedcomments/$', 'cafe.cafe_core.views.get_blacklistedcomments'),
	(r'^adminpanel/bannedusers/$', 'cafe.cafe_core.views.get_bannedusers'),
	(r'^adminpanel/userdetails/$', 'cafe.cafe_core.views.get_userdetails'),
	(r'^adminpanel/statistics/$', 'cafe.cafe_core.views.get_statistics'),
	(r'^adminpanel/generateplot/$', 'cafe.cafe_core.views.custom_statistics'),
	(r'^adminpanel/getdata/(?P<timeperiod>\w{0,50})/$', 'cafe.cafe_core.views.get_adminpanel_stats'),
    (r'^adminpanel/subgroup/$', 'cafe.cafe_core.views.get_subgroupplot'),
    (r'^adminpanel/getsubgroup/$', 'cafe.cafe_core.views.get_subgroup_data'),
    (r'^adminpanel/suggestion/$', 'cafe.cafe_core.views.get_suggestions'),
    (r'^adminpanel/configure/$', 'cafe.cafe_core.views.configure_client'),
	(r'^adminpanel/install/$', 'cafe.cafe_core.views.install_client'),
	(r'^adminpanel/proofread/$', 'cafe.cafe_core.views.proof_read_comments'),
	(r'^adminpanel/$', 'cafe.cafe_core.views.admin_panel_login'),

    # JSON pages
    (r'^os/list/$', 'cafe.cafe_core.views.os_list'),
    (r'^os/show/(\d+)/$', 'cafe.cafe_core.views.os_show'),
    (r'^os/show/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_show'),
    (r'^os/otherusers/(\d+)/$', 'cafe.cafe_core.views.os_other_users'),
    (r'^os/otherusers/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_other_users'),

    (r'^os/all/(\d+)/$', 'cafe.cafe_core.views.os_all_current_comments'),
    (r'^os/all/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_all_current_comments'),
    (r'^os/unrated/(\d+)/$', 'cafe.cafe_core.views.os_unrated_comments'),
    (r'^os/unrated/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_unrated_comments'),
    (r'^os/leaderboard/(\d+)/$', 'cafe.cafe_core.views.os_leaderboard_comments'),
    (r'^os/leaderboard/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_leaderboard_comments'),
    (r'^os/rated/(\d+)/$', 'cafe.cafe_core.views.os_rated_comments'),
    (r'^os/rated/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_rated_comments'),
    (r'^os/ratedby/(\d+)/$', 'cafe.cafe_core.views.os_rated_by_comments'),
    (r'^os/ratedby/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_rated_by_comments'),
	(r'^os/userlist/(\d+)/$', 'cafe.cafe_core.views.os_user_list'),
	(r'^os/userlist/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_user_list'),

    (r'^os/landmarks/(\d+)/$', 'cafe.cafe_core.views.os_landmarks'),
    (r'^os/getpreviouscomment/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_get_previous_comment'),
    (r'^os/getuserinfo/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_get_user_info'),
    (r'^os/getlandmarkratings/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_get_landmark_ratings'),
    (r'^os/getcomment/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_get_comment'),
    (r'^os/getcomment/(\d+)/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_get_comment'),
	(r'^os/getreceivedsuggestions/(\d+)/$', 'cafe.cafe_core.views.os_get_received_suggestions'),
	(r'^os/getreceivedsuggestions/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_get_received_suggestions'),
	(r'^os/getgivensuggestions/(\d+)/$', 'cafe.cafe_core.views.os_get_given_suggestions'),
	(r'^os/getgivensuggestions/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_get_given_suggestions'),
	(r'^os/savesuggestionrating/$', 'cafe.cafe_core.views.os_save_suggestion_rating'),
    (r'^os/flagcomment/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_flag_comment'),
    (r'^os/saveratings/(\d+)/$', 'cafe.cafe_core.views.os_save_ratings'),
    (r'^os/saverating/(\d+)/$', 'cafe.cafe_core.views.os_save_rating'),
    (r'^os/savecomment/(\d+)/$', 'cafe.cafe_core.views.os_save_comment'),
    (r'^os/savecomment/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_save_comment'),
    (r'^os/savecommentrating/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_save_comment_rating'),
    (r'^os/savecommentrating/(\d+)/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_save_comment_rating'),
    (r'^os/savecommentagreement/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_save_comment_agreement'),
    (r'^os/savecommentagreement/(\d+)/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_save_comment_agreement'),
    (r'^os/savesuggestion/$', 'cafe.cafe_core.views.os_save_comment_suggestion'),
    (r'^os/updateusersettings/$', 'cafe.cafe_core.views.os_update_user_settings'),
    (r'^os/firsttime/(\d+)/$', 'cafe.cafe_core.views.os_save_first_time_ratings'),
	(r'^os/stats/(\d+)/$', 'cafe.cafe_core.views.get_stats'),
	(r'^os/stats/(\d+)/(\d+)/$', 'cafe.cafe_core.views.get_stats'),
	(r'^os/notifications/(\d+)/$', 'cafe.cafe_core.views.get_notifications'),
	(r'^os/notifications/(\d+)/(\d+)/$', 'cafe.cafe_core.views.get_notifications'),
	(r'^os/neverseencomments/(\d+)/$', 'cafe.cafe_core.views.os_never_seen_comments'),
	(r'^os/neverseencomments/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_never_seen_comments'),
	(r'^os/ratedupdatedcomments/(\d+)/$', 'cafe.cafe_core.views.os_rated_updated_comments'),
	(r'^os/ratedupdatedcomments/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_rated_updated_comments'),
    (r'^os/updatecomment/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_update_comment'),
    (r'^os/updatecomment/(\d+)/(\d+)/(\d+)/$', 'cafe.cafe_core.views.os_update_comment'),
    
    
    # Admin
    (r'^admin/comments/$', 'cafe.cafe_core.admin.comment_admin'),
	# New Logs
	(r'^log/httperror/$', 'cafe.cafe_core.views.log_http_error'),
	(r'^log/userevent/$', 'cafe.cafe_core.views.log_user_event'),
	(r'^log/commentview/$', 'cafe.cafe_core.views.log_comment_view'),
	(r'^log/firsttime/$', 'cafe.cafe_core.views.os_first_time_log'),

    # SMS
	(r'^os/receivesms/$', 'cafe.cafe_core.views.os_receive_sms_comment'),
	
	#Close
	(r'^os/applicationclose/$', 'cafe.cafe_core.views.application_close'),
)
